// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Allergy struct {
	ID           string  `json:"id"`
	Name         string  `json:"name"`
	Symptoms     string  `json:"symptoms"`
	Severity     string  `json:"severity"`
	Treatments   *string `json:"treatments"`
	Notes        *string `json:"notes"`
	AllergyImage *string `json:"allergyImage"`
	IsActive     *bool   `json:"isActive"`
	CreatedBy    string  `json:"createdBy"`
	UpdatedBy    *string `json:"updatedBy"`
	DeletedBy    *string `json:"deletedBy"`
}

type NewAllergy struct {
	Name         string  `json:"name"`
	Symptoms     string  `json:"symptoms"`
	Severity     string  `json:"severity"`
	Treatments   *string `json:"treatments"`
	Notes        *string `json:"notes"`
	AllergyImage *string `json:"allergyImage"`
	IsActive     *bool   `json:"isActive"`
	CreatedBy    string  `json:"createdBy"`
}

type NewUser struct {
	Email    string `json:"email"`
	FullName string `json:"fullName"`
	Password string `json:"password"`
}

type UpdateUser struct {
	Email    *string `json:"email"`
	FullName *string `json:"fullName"`
}

type User struct {
	ID       string `json:"id"`
	Email    string `json:"email"`
	FullName string `json:"fullName"`
	Password string `json:"password"`
}
